services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn pulse.wsgi:application --bind 0.0.0.0:8000
    container_name: web
    volumes:
      - ./pulse:/app/pulse
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  celery:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A pulse worker --loglevel=info
    container_name: celery
    volumes:
      - ./pulse:/app/pulse
      - media_volume:/app/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:18.0
    container_name: db
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:8.2.2
    container_name: redis
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
