services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: web
    volumes:
      - ./pulse:/app/pulse
      - media_volume:/app/mediafiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A pulse worker --loglevel=info
    container_name: celery
    volumes:
      - ./pulse:/app/pulse
      - media_volume:/app/mediafiles
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:18.0
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:8.2.2
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  media_volume:
